# SITE CONFIGURATION
title: Ju # your site title
author: juditina # You :P
description: > # Meta description of Homepage
  Personal website where I show my projects and write about stuff I'm trying to understand
# baseurl: "/sleek" # the subpath of your site, e.g. /blog
url: "https://juditina.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Ju
  links:
    - https://github.com/juditina

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Blog', link: '/blog'}

tagline: >
  Currently studying Computer Science

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

# twitter_username: # replace with your_twitter_username or comment to remove link from footer
github_username:  juditina # replace with your_github_username or comment to remove link from footer
# instagram_username: # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: judith2v # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
